-- AlterTable
ALTER TABLE "feasts" ALTER COLUMN "start" DROP NOT NULL,
ALTER COLUMN "start" DROP DEFAULT,
ALTER COLUMN "start" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "end" DROP NOT NULL,
ALTER COLUMN "end" DROP DEFAULT,
ALTER COLUMN "end" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "closed" DROP NOT NULL;
